# Generated by Django 5.1.2 on 2024-11-15 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0002_alter_geodata_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geodata",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
